var FilterConstants = {
  UPDATE_BOUNDS: "UPDATE_BOUNDS",
  UPDATE_MIN_SLEEP_NUM: "UPDATE_MIN_SLEEP_NUM",
  UPDATE_ROOM_TYPE: "UPDATE_ROOM_TYPE",
  UPDATE_PRICE_RANGE: "UPDATE_PRICE_RANGE",
  UPDATE_START_DATES: "UPDATE_START_DATES",
  UPDATE_END_DATES: "UPDATE_END_DATES",
  RESET_DATES: "RESET_DATES"
};

module.exports = FilterConstants;
