var FilterConstants = {
  UPDATE_BOUNDS: "UPDATE_BOUNDS",
  UPDATE_MIN_SLEEP_NUM: "UPDATE_MIN_SLEEP_NUM",
  UPDATE_ROOM_TYPE: "UPDATE_ROOM_TYPE",
  UPDATE_PRICE_RANGE: "UPDATE_PRICE_RANGE",
  UPDATE_DATES: "UPDATE_DATES",
  RESET_DATES: "RESET_DATES"
  // UPDATE_MAX_SLEEP_NUM: "UPDATE_MAX_SLEEP_NUM"
};

module.exports = FilterConstants;
